apiVersion: v1
kind: Service
metadata:
  name: users
spec:
  selector: { app: users }
  ports:
  - name: http
    port: 8000
    targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
spec:
  replicas: 1
  selector: { matchLabels: { app: users } }
  template:
    metadata:
      labels: { app: users }
    spec:
      containers:
      - name: app
        image: zt-demo-fastapi:1.0
        imagePullPolicy: IfNotPresent
        env:
        - { name: SERVICE_NAME, value: "users" }
        - { name: EXP_ID, value: "exp-secure-001" }
        ports:
        - containerPort: 8000
